name: Build

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  cancel:
    name: 'Cancel previous runs'
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

  build:
    name: 'Build and test'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm test
